version: "3"
services:
  nuxt-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../src:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0