version: "3"
services:
  nuxt-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../src:/app:cached
      - /app/node_modules
    ports:
      - "80:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules: